### ISSUE TITLE
Broken on MacOS Sierra

### ISSUE THREAD

**Issue by Isaac-Newt** [wilfredwee/photon-australis#1]
This style is broken on MacOS.  Tested on Sierra (10.12), might apply to other versions as well.

Screenshot:

![screen shot 2017-10-02 at 6 43 31 pm](https://user-images.githubusercontent.com/29472511/31104287-c4101f84-a7a1-11e7-92c5-987b39d0f232.png)

**Comment by wilfredwee** [comment]
It currently only supports the dark theme. Seems like the white/default theme has many users, I'll look into providing a white theme implementation :)

**Comment by wilfredwee** [comment]
Hi, sorry for the delay. Life has been busy.

You should be able to enjoy curved tabs with the Default or Light theme now, as of [v0.2.1](https://github.com/wilfredwee/photon-australis/tree/v0.2.1).

Enjoy! :)
