### ISSUE TITLE
Tabs are still square

### ISSUE THREAD

**Issue by noconflicts** [wilfredwee/photon-australis#100]
Howdy.  I followed the directions  you gave to the letter. I am attempting to bring back the rounded tabs to the Portable Firefox Quantum ESR 68.8Desr (64 bit).  Still have the square tabs. Any chance that the instructions will not work for this version?  I know that they do work as I modified my FF at work the same way and it worked perfectly.  Thanks!

**Comment by noconflicts** [comment]
Howdy. I believe I figured it out. I had to add the chrome folder and the css file to the profile created for the portable version as well as in the Roaming profile. That seems to have done the trick.  Thanks.

**Comment by wilfredwee** [comment]
Glad you solved your issue!
