### ISSUE TITLE
Request: Multi-row window tabs

### ISSUE THREAD

**Issue by Cat22** [wilfredwee/photon-australis#101]
Firefox 78.0.2 x86_64 (linux)
I had multi-row tabs but the code isn't compatible with yours so they get completely destroyed when i try to combine the two.
The tabs in my existing userChrome work fine, but look awfully clunky which is why I wanted to use your more aesthetically pleasing code.
Can you add multi-row tabs to your userChrome.css files? 
I already have a multi-row bookmarks toolbar that works well 
I have attached my userChrome.css that gave me multi-row tabs and bookmarks just in case its useful (_not_ my own creation - dl'd from net)
[userChrome.css.multi-row.txt](https://github.com/wilfredwee/photon-australis/files/4908139/userChrome.css.multi-row.txt)

**Comment by wilfredwee** [comment]
Hello, unfortunately I'm not able to support multi-row tabs.
