### ISSUE TITLE
It's not working...

### ISSUE THREAD

**Issue by Zaza-Canada** [wilfredwee/photon-australis#104]
I did everything you said in the instructions, but everytime i restart the browser, it is still the same. How may I fix this?
![image](https://user-images.githubusercontent.com/70673816/105789251-13414880-5f50-11eb-895a-dca15400bd96.png)
![image](https://user-images.githubusercontent.com/70673816/105789268-1b00ed00-5f50-11eb-9181-ae27aab5a2c7.png)
![image](https://user-images.githubusercontent.com/70673816/105789301-2d7b2680-5f50-11eb-868a-a37de0ce91e3.png)

**Comment by googolplexxx** [comment]
Try renaming `userChrome-dark.css` to `userChrome.css`.  
Worked for me

**Comment by Zaza-Canada** [comment]
> Try renaming `userChrome-dark.css` to `userChrome.css`.
> Worked for me

Just applied your suggestions and nothing still:

![image](https://user-images.githubusercontent.com/70673816/105915707-054a0100-5ffe-11eb-9787-1a3051776525.png)

**Comment by wilfredwee** [comment]
Hi, did you try restarting the browser after you made the changes?

**Comment by Zaza-Canada** [comment]
Yes so I closed the browser and then pressed it again to open it up. There
were no changes for some reason.

**Comment by wilfredwee** [comment]
Can you try making sure that you copied the text correctly, using this link: https://raw.githubusercontent.com/wilfredwee/photon-australis/master/userChrome-dark.css

Ctrl+A to select all.
Ctrl+C to copy

Open your `userChrome.css` file using a text editor and

Ctrl+A to select all
Delete/Backspace to delete everything.

Ctrl + V to paste.

Save, restart browser.

**Comment by wilfredwee** [comment]
Also, make sure you select the correct profile in `about:profiles`. It should be under `This is the profile in use and it cannot be deleted.`

**Comment by Zaza-Canada** [comment]
Alright, so I had to go into file manager settings and allow for filename extensions. Now when I rename something to ".css" it actually saves as a CSS file. All of your code works perfectly fine now. Thank you, @wilfredwee for making this nice userChrome, and also thank you for your help.
