### ISSUE TITLE
Customize toolbars size other than "Normal"<==

### ISSUE THREAD

**Issue by ghost** [wilfredwee/photon-australis#109]
So when I go to "customize toolbars" and increase the "Density" to anything other than "normal", the tabs themselves do not really seem to increase as per the option selected. Actually they seem to overlap into the address bar. So my question is, do you know of a way to lower the address bar to accommodate the size of the tabs? I mean I was assuming this was supposed to be like a Google chrome themed mod, but GC has bigger tabs than this..

**Comment by wilfredwee** [comment]
Hello, only Normal Density is supported in this theme due to how the tab code is structured.
