### ISSUE TITLE
tabbrower-tab has an extra dark space below

### ISSUE THREAD

**Issue by kanehekili** [wilfredwee/photon-australis#111]
Thank you for maintaining photon-australis. I'm using this css file for a long time. Today I've copied the newest theme unto Firefox 89 on Linux. (XFCE desktop)
A small glitch can be seen:
![image](https://user-images.githubusercontent.com/4390452/120706468-6d7f8680-c4b9-11eb-965d-b41721e3da12.png)

at the bottom. Any idea why that happens or how to get rid of it ? 

I have the "toolkit.legacyUserProfileCustomizations.stylesheets" set to true (to get chrome.css back) 
+ svg.context-properties.content.enabled true
+  browser.compactmode.show true

**Comment by Koukotsukan** [comment]
I met this problem too and just now I found this
https://github.com/wilfredwee/photon-australis/issues/90

**Comment by Koukotsukan** [comment]
The solution works for me is go to about:config
then set browser.uidensity to 1

**Comment by kanehekili** [comment]
I'm not sure anymore, but I've removed 
+ layers.acceleration.force-enabled ->true 
+ layers.accelerate-all ->true
+ gfx.canvas.azure.accelerated ->true
and the tabs look right.
