### ISSUE TITLE
Tab highlights only a small part

### ISSUE THREAD

**Issue by Admiralmatt** [wilfredwee/photon-australis#112]
After the new update (89.0) all tabs look like this where it makes a small part white and the rest black.
<img width="1115" alt="Screen Shot 2021-06-05 at 11 55 36 PM" src="https://user-images.githubusercontent.com/9373482/120912036-ed445700-c659-11eb-9042-7b7742779f9d.png">

It used to look like this where the entire tab is highlighted. 
![screen-1](https://user-images.githubusercontent.com/9373482/120912070-3694a680-c65a-11eb-9228-3a271580ef27.png)

**Comment by Admiralmatt** [comment]
since then i have applied the "How do I add back tab separators and borders around the tabs?" fix https://www.reddit.com/r/FirefoxCSS/comments/bzd5dz/help_with_australis_css/

that fix seems to have helped a bit. it now looks like this 
<img width="848" alt="Screen Shot 2021-06-07 at 12 33 18 PM" src="https://user-images.githubusercontent.com/9373482/121057063-dfdbb980-c78c-11eb-811a-ac8be4c77f8c.png">
and is much better then it was before but is still a bit off. still hoping for a fix to have the top border as well.

**Comment by wilfredwee** [comment]
Hello, be sure to use the latest code to account for the new Firefox release: https://github.com/wilfredwee/photon-australis/tree/v1.0
