### ISSUE TITLE
Increase Drag Space Above Tabs?

### ISSUE THREAD

**Issue by githubaccount101** [wilfredwee/photon-australis#113]
In older firefox versions i added 

#tabbrowser-tabs {margin-top: 10px !important}

to the usechrome file to achieve this.

However now it just pushes the tabs physically down. Naturally this increases the drag space but obviously looks hideous.

Is there a way to increase the space between the tab and the top of the window?

(i don't know any css)

**Comment by wilfredwee** [comment]
Hello, unfortunately I'm not able to help with this. Maybe the kind folks at https://www.reddit.com/r/FirefoxCSS/ might be able to help.
