### ISSUE TITLE
too small close button

### ISSUE THREAD

**Issue by CO-Windler** [wilfredwee/photon-australis#114]
I have combined photon-australis with CustomCSSforFx using a different close icon.
`@import "./css/generalui/close_icon_firefox3.css"`

I have included it in my_userChrom.css launched from the userChrome.css of "Aris-t2/CustomCSSforFx". Initially (FF89?) this worked well, but now the tab close button is displayed too small. I have a greenish Firefox theme installed and use the light version userChrome-light_photon-australis.css.

my_userChrom.css:
@import url(userChrome_Fx56_bookmark_icons.css); /* bookmark icons */
@import url(userChrome-light_photon-australis.css); /* curved tabs */

(Important is to disable the internal tab styles of CustomCSSforFx, else it displays garbage.)

**Comment by wilfredwee** [comment]
Hello, unfortunately I'm not familiar with the CSS fix. Feel free to reach out to the kind folks at https://www.reddit.com/r/FirefoxCSS/
