### ISSUE TITLE
Does photon-australis exist as a KDE/GTK theme?

### ISSUE THREAD

**Issue by CO-Windler** [wilfredwee/photon-australis#115]
I have modded my KDE5 Plasma and Cinnamon (Linux Mint 20.1) into a sort of Vista theme.

Does something like photon-australis exist as an addon for KDE or GTK? Or is it possible to mod the given themes (Vista/Win7 Aero Glass style) to draw such tabs? The blocky default KDE tabs look truly ugly.

**Comment by wilfredwee** [comment]
Hello, as far as I know this is not possible, as FF themeing is specific to Firefox.
