### ISSUE TITLE
Revert the distracting download circle with the original down arrow

### ISSUE THREAD

**Issue by Yanta0205** [wilfredwee/photon-australis#116]
Using FF 91 esr. 
The download icon changes to a filling circle whilst downloading. My users are complaining the find it ugly and distracting and want the down arrow back for all downloads. Is this possible?

**Comment by wilfredwee** [comment]
Hello, this is not within scope of this project. Feel free to reach out to the kind folks at https://www.reddit.com/r/FirefoxCSS/
