### ISSUE TITLE
FF 92 no sexy tabs

### ISSUE THREAD

**Issue by StormJumper** [wilfredwee/photon-australis#117]
I just reimaged on computer and installed FF92x64 but I can't get the sexy tab back? What am I missing? My Desktop just doing a upgrade as the previous comments still has the sexy tabs so what happened? That Laptop version has the square tabs not the curve as my Desktop version and both are FF92.

**Comment by wilfredwee** [comment]
Hello, make sure that you have followed the instructions closely:
> Go to your Firefox browser, type about:config in your url bar.
Search for toolkit.legacyUserProfileCustomizations.stylesheets and set it to true
