### ISSUE TITLE
Too much bright white tab

### ISSUE THREAD

**Issue by peekaa** [wilfredwee/photon-australis#13]
Could be that active tab is not so white/bright? It shines too much.... 
![obrazek](https://user-images.githubusercontent.com/3026590/32879561-c9063a4c-caaa-11e7-9866-8b55d7b534ad.png)

Thank you.
W7

**Comment by wilfredwee** [comment]
Hey there, using custom Persona themes (your custom background) are not supported, and is probably too difficult/impossible to implement properly.

**Comment by peekaa** [comment]
I see. When using Default, I got his. 
![obrazek](https://user-images.githubusercontent.com/3026590/32880646-b556c4c2-caae-11e7-9f7f-ec0882ebbbfe.png)

**Comment by wilfredwee** [comment]
Are you using Win7 or Win8?

**Comment by peekaa** [comment]
win7

**Comment by wilfredwee** [comment]
This is a similar issue to #11 

Try using the latest release here: https://github.com/wilfredwee/photon-australis/tree/v0.2.2
and see if it fixes your problem.

I'll close this thread and consolidate discussions in the original thread. Thanks!
