### ISSUE TITLE
FF113: Curvy tabs completely garbled

### ISSUE THREAD

**Issue by CO-Windler** [wilfredwee/photon-australis#131]
I am using CustomCSSforFx for a Vista-like style that I combined with "photon-australis" (colours slightly edited) for curvy tabs. Since Firefox 113 on Linux Mint with KDE Plasma 5.18.8 the curved tabs now look completely garbled; the upper row with text and close button is drawn too high and halfway disappears, while the tab itself (except the right curved rim) is missing. Please fix this.

![Firefox113 garbage1_Detail](https://github.com/wilfredwee/photon-australis/assets/88873504/387911c1-d0a7-44a5-bc2f-41f6adaf1348)

**Comment by Orriky** [comment]
Replace all instances of `display: -moz-box` with `display: flex`
and `-moz-box-orient: horizontal` with `flex-direction: row`

**Comment by CO-Windler** [comment]
Thanks! It works again.

**Comment by Impakt** [comment]
they're better but not perfect 
<img width="254" alt="image" src="https://github.com/wilfredwee/photon-australis/assets/1773489/1d197910-07e5-4511-be37-8cc4e82fbafc">
