### ISSUE TITLE
Newtab icon shape has minor design flaw

### ISSUE THREAD

**Issue by teijiIshida** [wilfredwee/photon-australis#15]
There is a minor design flaw underneath the newtab icon. You can't really see it with your code because the newtab's alpha is set at 0.1, but if you increase the alpha you can see it clearly. See pic: https://i.imgur.com/oRDrBeD.jpg

**Comment by wilfredwee** [comment]
Yeah it's a bug I'm aware of. I'll see if I can fix it.

**Comment by teijiIshida** [comment]
I know that the shape is in the "svg shape d" portion of your code, but it's so hard to modify without the proper tool. Is there a specific tool or website that you use to edit the curve shape?

**Comment by wilfredwee** [comment]
Unfortunately no. I got the svg from previous version of Firefox. =\

**Comment by wilfredwee** [comment]
Hey there, this release should fix the problem: https://github.com/wilfredwee/photon-australis/tree/v0.3.0
