### ISSUE TITLE
too much space on left of pinned tabs

### ISSUE THREAD

**Issue by lonestaritaly** [wilfredwee/photon-australis#19]
Hello,
there is too much space on the left of the first pinned tab. Looks almost like there is an invisible pinned tab. The first pinned tab should be immediately at the border. How can it be fixed?

https://imagebin.ca/v/3hjM2iHPxUHq

**Comment by wilfredwee** [comment]
Hey there, this is due to the new drag space that Mozilla introduced. Fixing this will be tricky.

Feel free to fork or submit a PR!
