### ISSUE TITLE
Tab Background Issue?

### ISSUE THREAD

**Issue by cancodr** [wilfredwee/photon-australis#27]
Hey, I love your change to restore the tabs back!  However, I have a strange issue that the background of the tab remains dark.  I'm using Windows 7, could that be the problem?
![firefox_tabs](https://user-images.githubusercontent.com/16725931/33275142-15d51eb6-d360-11e7-9695-fa83e55ece27.jpg)

**Comment by teijiIshida** [comment]
It's a Firefox bug for Windows 7. See issue #11

**Comment by wilfredwee** [comment]
Indeed it is, I still couldn’t find someone with a windows 7 machine to debug this...

Closing this as duplicate and consolidating all discussions in #11
