### ISSUE TITLE
Can not copy/paste....

### ISSUE THREAD

**Issue by mad4some** [wilfredwee/photon-australis#28]
Hello, when I highlight and "copy" the required script for dark choice, the "paste" option is always greyed out when I try to paste in my userChrome.css folder. Windows 10/64bit PC.....any suggestions?? fixes??  Thanks, Mark

**Comment by wilfredwee** [comment]
Hi, userChrome.css is supposed to be a file, not a folder.

This is the official guide from Mozilla: http://kb.mozillazine.org/index.php?title=UserChrome.css

**Comment by mad4some** [comment]
Thank you!.....i'll give it a try.
