### ISSUE TITLE
blue bar over curved tab

### ISSUE THREAD

**Issue by veso266** [wilfredwee/photon-australis#29]
Hi I've realy like curved tabs but I also started to love this nice dark blue bar over a tab in firefox 57: https://i.redd.it/uh9xp2bjw7oz.png so I am wondering if its posible to add it back here so I could enjoy my favourite curves and also have blue bar like firefox 57 has?

Thanks for Anwsering and Best Regards

**Comment by wilfredwee** [comment]
The blue bar is part of Firefox's new Container Tabs. It's been requested before but I've not found a good way to implement this. Feel free to continue the discussions here: #4
