### ISSUE TITLE
Colored Tabs

### ISSUE THREAD

**Issue by aflove65** [wilfredwee/photon-australis#30]
Is there any way to color the actual tabs?

**Comment by wilfredwee** [comment]
Unfortunately due to how it's done right now there's no easy way, as you'll need to color the tab background AND the svg's for the curves.

Feel free to fork or submit a PR if you found a way!

**Comment by userOperaFF** [comment]
Dark theme with gray (`rgb(227, 227, 227)`) line:

```css
  --background-selected-middle:
    linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)),
    linear-gradient(
      transparent
      2px,
      rgb(227, 227, 227) 3px, /* gray line */
      rgb(50, 50, 52) 4px, /* fix height */
      rgb(50, 50, 52)
    ),
    none !important;
```

![obraz](https://user-images.githubusercontent.com/33114475/34270344-2bb759ac-e688-11e7-912b-5493c3ab8b89.png)


Active tab with line, no edit svg images yet.

And I have no idea how recover colors cointainers tab / use `.tab-line`.
