### ISSUE TITLE
Active tab name is black on "dark"

### ISSUE THREAD

**Issue by bartgrantham** [wilfredwee/photon-australis#31]
![screen shot 2017-12-17 at 9 30 51 pm](https://user-images.githubusercontent.com/913646/34091303-a6028016-e371-11e7-871b-d299f42739e5.png)

Inactive tabs draw correctly.  This is on FF 57.0.1 / macOS 10.12.6.

**Comment by wilfredwee** [comment]
Hmm, I can't reproduce this. Are you using the Dark theme? Are you using any other UI customization/tweaks?

**Comment by bartgrantham** [comment]
Nope.  Maybe running afoul of a rendering bug that happens on this GPU (Intel Iris)?  I'm also running an external display.  Neither GPU nor external display should make a difference, but I've seen weirder bugs.

**Comment by userOperaFF** [comment]
No bug with old amd procesor on Windows 10.

**Comment by wilfredwee** [comment]
Can you please provide a screenshot of the entire browser window?

**Comment by bartgrantham** [comment]
Here's an example.  The third tab is the active one, showing this thread.

<img width="978" alt="screen shot 2017-12-23 at 12 54 18 am" src="https://user-images.githubusercontent.com/913646/34318412-dd35abc2-e77b-11e7-9ae0-3a203211a453.png">

**Comment by wilfredwee** [comment]
You're using `userChrome-dark.css` with Firefox's default theme. You should either use `userChrome-default.css` or use Firefox's dark theme.
