### ISSUE TITLE
Bring Compact Australis back too!

### ISSUE THREAD

**Issue by zakius** [wilfredwee/photon-australis#33]
The minimalist, square tabs are great, but not the glowing ones Photon brought!

And there's much more to be done besides disabling that colored bar at the top, everything is broken in Photon

**Comment by userOperaFF** [comment]
Zrób lepsze 👍

**Comment by wilfredwee** [comment]
Thanks for the feedback. This sounds like a good idea for a separate project, as this project focuses solely on re-introducing curved tabs in Firefox.
