### ISSUE TITLE
Photon-australis modification of colors ?

### ISSUE THREAD

**Issue by qwerty963** [wilfredwee/photon-australis#39]
Hello, I have a question whether it is possible to change colors in the css code
photon-australis dark. Tab to change to any color of the card and that there is no background in the address bar and bookmarks?

**Comment by wilfredwee** [comment]
Hello, this should be possible, but it's not part of the goal of this project.

Feel free to fork and create your own flavor!

**Comment by qwerty963** [comment]
And at least I can ask for a fragment of the CSS code that is responsible for the background color in the address bar and tabs and card colors

**Comment by qwerty963** [comment]
I would just like to change the backlight-background in which the address bar and tabs are, so that it is not transparent or transparent.

**Comment by wilfredwee** [comment]
Currently the project just uses the default background color that comes with the theme (it's set to transparent). Unfortunately I wouldn't call myself an expert in this are, you may find more resources and help through these links:

https://www.reddit.com/r/FirefoxCSS/
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Modifying_the_Default_Skin
http://kb.mozillazine.org/index.php?title=UserChrome.css

good luck!

**Comment by qwerty963** [comment]
One more question about the style of how to change the location of the cards in order to be under the address bar.
