### ISSUE TITLE
Seems broken in FF 58.0.2 (64bit)

### ISSUE THREAD

**Issue by Johnich** [wilfredwee/photon-australis#40]
It doesn't work in Firefox 58.0.2 (64bit). 
Environment: macOS High Sierra 10.13.4

**Comment by wilfredwee** [comment]
Hi there, could you provide more information? I'm on FF 60 Sierra, I don't have any problems.

**Comment by krystian3w** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/101
