### ISSUE TITLE
Light theme looks a bit weird on Windows 7

### ISSUE THREAD

**Issue by IceMan81** [wilfredwee/photon-australis#41]
The tabs are curved but the first and last tabs are curved inside a white background that is squarish. So if the first tab is inactive, then it actually just looks like a square tab. 

Unfortunately I'm unable to attach a screenshot - keeps failing on github

**Comment by vadosnaprimer** [comment]
![tabs](https://user-images.githubusercontent.com/7092625/37535969-53c3f5d0-295a-11e8-8101-9284ee5d2fdf.png)

**Comment by IceMan81** [comment]
@vadosnaprimer Thanks for adding the screenshot.

**Comment by wilfredwee** [comment]
Hello, thanks for reporting the bug!

This latest release fixes the problem: https://github.com/wilfredwee/photon-australis/releases/tag/v0.3.3 

Let me know if you have further questions.
