### ISSUE TITLE
Curves not working???

### ISSUE THREAD

**Issue by mad4some** [wilfredwee/photon-australis#42]
Hello, I have used your curved tabs successfully on my pc and a laptop running FF 57+  Just yesterday I had to do a Windows 10 reset in order to fix a boot/update issue and have now reinstalled the latest 59.0.1 FF and doing the same profile creation and cut and paste is not working anymore??? Do you know of a FF change that would be causing this?? Thanks for your time and work!!  Mark

**Comment by wilfredwee** [comment]
That’s very weird, CSS shouldn’t cause any changes to functionality. I don’t currently have this problem. Perhaps it’s a problem with your FF installation?
I’ll test further in a bit.

**Comment by wilfredwee** [comment]
Yeah definitely cut and paste working here. Will close this unless more people have the same issue. Good luck in solving this!

**Comment by mad4some** [comment]
Hello and thanks for your help......and sorry for the delay checking my
emails!! What it was is that I had deleted the built in Office app from my
new update to Windows 10 and even though all the actions of copy/paste
looked normal they were not actually happening in the background I guess
(?) Once I installed OpenOffice (which I always do) and did it again, it
worked with no issue!!  Thanks again, and sorry for the slight "goose
chase"     Mark

**Comment by wilfredwee** [comment]
No worries. Enjoy :)
