### ISSUE TITLE
Active tab text is not visible

### ISSUE THREAD

**Issue by IceMan81** [wilfredwee/photon-australis#43]
Active tab text is not visible in both dark and light themes. This is related to https://github.com/wilfredwee/photon-australis/issues/41

<img width="282" alt="screen shot 2018-03-19 at 11 27 58 pm" src="https://user-images.githubusercontent.com/1093778/37639106-4e378b7a-2bcd-11e8-8224-433f763fa851.png">

**Comment by wilfredwee** [comment]
Looks like you’re usin the dark css theme with Firefox default theme. You’ll need to match the css theme with your current Firefox theme

**Comment by IceMan81** [comment]
@wilfredwee you were right. Sorry about that, fixed the issue.
