### ISSUE TITLE
Tabs container looks to be padded on the left

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [wilfredwee/photon-australis#45]
Xubuntu 18.04; Firefox 59.02; 64bit
This makes it look right, maybe you have a better less hackish fix?
```
#tabbrowser-tabs{
	margin-left:-15px;
}
```

**Comment by wilfredwee** [comment]
Looks good! I believe I left it as it is before to allow for more space for the mouse to click and drag. This looks to be a more faithful implementation of the actual Firefox looks so I'll add it in.

**Comment by wilfredwee** [comment]
https://github.com/wilfredwee/photon-australis/releases/tag/v0.4.1

Thanks! Resolving.
