### ISSUE TITLE
Tab color is slightly off

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [wilfredwee/photon-australis#46]
Default firefox theme Xubuntu 18.04

The background color should be: `var(--toolbar-bgcolor)` but i am getting a color of code of `#f9f9ff` aka `rgb(249,249,255)` instead of `#e3e3e3` aka `rgb(227,227,227)`
i was able to use use the variable color under `--background-selected-middle` but i had to hard code it in the svg data
Would It be possible to use the `--toolbar-bgcolor` variable in the svg uri?

**Comment by wilfredwee** [comment]
As far as I know it’s not possible to use CSS variables in SVG, without some kind of preprocessor. Would welcome ideas though.

- Wilfred

Sent from mobile.
________________________________

**Comment by wilfredwee** [comment]
This project is on bugfix maintenance only. Closing as wontfix.
