### ISSUE TITLE
'New Tab' button is partially obscured by tab to the left

### ISSUE THREAD

**Issue by bpinkney** [wilfredwee/photon-australis#47]
<img width="297" alt="newtabbutton hidden" src="https://user-images.githubusercontent.com/6341361/39730027-2d0ee94e-522d-11e8-81c0-78ae1c5abb4f.png">

The 'new tab' '+' button is obscured by the tab to the left of it.
The result is that the cursor must be on the right side of the '+' before the button is clickable.
(hover for the 'new tab' button is shown with a red background, the 'tab-stack' background is in yellow.)

I am unsure if this can be solved by applying the 'z-index' property.

**Comment by bpinkney** [comment]
Looks like you can indeed push this up with the 'z-index' property, so long as you also mark the position as relative:
```
#new-tab-button,
.tabs-newtab-button {
  width: calc(36px + 30px) !important;
  margin-inline-start: -15px !important;
  margin-top: 1px !important;
  z-index: 10;
  position: relative;  
}
```

**Comment by wilfredwee** [comment]
Thanks for the code snippet! I’ll take a look in the weekend when I have some time.

I think I’ve tried this approach before but the left part of the new tab button will not be hidden behind the tab on the left. That’s inconsistent with Australis design. I will take a further look into negative margins and see if I can solve this.

**Comment by wilfredwee** [comment]
Found a permanent fix to the hovering issue. All hovering actions should be better now, including the newtab behavior.

https://github.com/wilfredwee/photon-australis/releases/tag/v0.4.0

Feel free to re-open the issue if you find the new behavior is unsatisfactory. :)
