### ISSUE TITLE
Windows 10 Tablet Mode

### ISSUE THREAD

**Issue by michaelhq** [wilfredwee/photon-australis#49]
Hello

There is a gap shwon between a tab and the bar below when window is switched to tablet mode. 

Could it be fixed?

Best regards
Mkichael

**Comment by wilfredwee** [comment]
Hey there. I've played around with tablet mode and it seems like the tab heights are much larger. I'll take a took when I have some time, though I am quite busy these days!

**Comment by wilfredwee** [comment]
This project is on bugfix maintenance only. Closing as wontfix.
