### ISSUE TITLE
Having full set of tabs triggers tab overflow UI

### ISSUE THREAD

**Issue by ntucker** [wilfredwee/photon-australis#5]
If you have enough tabs to take the full width, but not actually need scrolling (because they shrink in size), you'll be annoyed with the existence of a constant slight overflow that triggers the tag scrolling mechanism. Adding or removing tabs won't change the amount of overflow because the tabs are adjusted in size as you move.
I suspect this has to do with the curves being slightly larger than firefox expects. Maybe put some negative margin in?

**Comment by wilfredwee** [comment]
Yeah there's something that I've not really figured out with the margins/sizes of the tabs. The overflow is not behaving properly. I will take a look when I'm able to.

(Feel free to create a pull request if you have it figured out!)

**Comment by wilfredwee** [comment]
Hey there, this release should fix the problem: https://github.com/wilfredwee/photon-australis/tree/v0.3.0

**Comment by ntucker** [comment]
Thanks!
