### ISSUE TITLE
Vivaldifox

### ISSUE THREAD

**Issue by johnnydement** [wilfredwee/photon-australis#50]
Best feature of vivaldi aesthetics is to be able to make the current tab color go alongside content, vivaldi fox does that for firefox.

https://addons.mozilla.org/es/firefox/addon/vivaldifox/?src=userprofile

Unfortunatelly, with modified userchrome the tab part does not color alongside the rest of the page.

![sin titulo](https://user-images.githubusercontent.com/1867306/42644496-0a079bdc-85fc-11e8-93f9-a34d0161a989.png)

**Comment by wilfredwee** [comment]
Hi there, sorry for the late reply.

Unfortunately, this is not possible without custom JS. I've heard of hacks where you can still use custom JS in FF 57+ but I've not looked into it much.

Will welcome PRs or forks!
