### ISSUE TITLE
Thunderbird 60

### ISSUE THREAD

**Issue by peekaa** [wilfredwee/photon-australis#51]
Is there possibility to have this available even in new Thunderbird 60? Thank you.

**Comment by wilfredwee** [comment]
Interesting idea
![capture](https://user-images.githubusercontent.com/3768039/43987881-6cef9d9c-9cdd-11e8-9364-aba05a1ff958.PNG)

Unfortunately it looks like it requires quite a bit of work tho =\

I'll see if I have some time to take a look.

**Comment by wilfredwee** [comment]
This project is on bugfix maintenance only. Closing as wontfix.
