### ISSUE TITLE
Close Tab Button Circular Hover

### ISSUE THREAD

**Issue by qingxiang-jia** [wilfredwee/photon-australis#52]
It's great we can stay with Australis, thanks for the efforts. I notice one thing: when you hover over the "Close this tab" button on the tab, it's shaped as a square with rounded corner, would it be better if we have simply a circle? Here is a comparison, the new Chrome UI and and Photon Australis.

![chrome](https://user-images.githubusercontent.com/5571586/44304105-3ee39180-a307-11e8-86c5-1316def2be6e.png)
new Chrome UI

![firefox](https://user-images.githubusercontent.com/5571586/44304106-430faf00-a307-11e8-968d-d421ff2ff956.png)
Photon Australis

I am not sure if it's possible as I didn't find anything dealing with that close button in the CSS file.

**Comment by wilfredwee** [comment]
Hi there,

Sorry for the late reply. Been quite busy lately. Thanks so much for the feedback! I agree that a circle hover icon is much better and it is now implemented in the latest release: https://github.com/wilfredwee/photon-australis/releases/tag/v0.5
