### ISSUE TITLE
Animation on tabs is still for square tabs

### ISSUE THREAD

**Issue by qingxiang-jia** [wilfredwee/photon-australis#53]
If you refresh a page, the tab will have an animation of blue bar quickly moving through that tab. That animation is designed for the squared tab, it doesn't match the curved tab and thus looks ugly. To avoid the visual disturbance, we can disable `toolkit.cosmeticAnimations` in `about:config`. Is it possible to fix that by altering userChrome.css?

Thanks.

**Comment by wilfredwee** [comment]
Hi there,

Thanks again for your feedback! I've finally gone round to disabling this animation. I agree it's cleaner. It's now fixed in the latest release: https://github.com/wilfredwee/photon-australis/releases/tag/v0.5
