### ISSUE TITLE
Context menu has a dead-zone

### ISSUE THREAD

**Issue by Goldoche** [wilfredwee/photon-australis#54]
I don't know if this is still maintained but I found an issue with the context menu.

![firefox context menu](https://user-images.githubusercontent.com/16695806/45270152-e3b94080-b467-11e8-9363-4c9a3e4bc5f7.png)

You can fix that by removing 
`.arrowscrollbox-scrollbox {
  padding-inline-start: 10px !important;
}
`
but then the clicking areas for some "X" buttons on the tabs are misaligned.

Thank you!

**Comment by wilfredwee** [comment]
Hi there,

Sorry for the late reply. Thanks for pin-pointing the troublesome CSS! I've fixed this in the latest release: https://github.com/wilfredwee/photon-australis/releases/tag/v0.5
