### ISSUE TITLE
No Issue with code, but...

### ISSUE THREAD

**Issue by RockyFaher** [wilfredwee/photon-australis#56]
Although I don't code anymore, (I was a self taught amateur that wrote proprietary, full scale Visual Basic applications for industrial test platforms in a high-speed manufacturing environment), I do appreciate good programming, but I have to say; CLARITY is everything.  'Clarity' as in documentation.  Maybe I'm slow (or worse; just old), but somewhere in your 'rough instructions' for injecting the code 'userChrome-dark.css' module, you might actually say "Copy the code contained inside 'userChrome-dark.css'  and paste it into the 'userChrome.css' somewhere under the namespace reference line of code.  Because, believe it or not I just pasted the entire 'userChrome-dark.css' file into the 'chrome' folder because it had the 'css' filename extension and I assumed it was a standalone code module that would be automatically picked up by the XML engine as the files in the tree were parsed.  My method of course did not work and your code did not work until I copied and pasted the raw lines of code from 'userChrome-dark.css' into the 'userChrome.css' file.  Sometimes you have to make allowances for non-programmers and idiots like me by being a _little_ more specific.  Hope this doesn't ruffle your feathers, but some other people out here might appreciate the notation.

**Comment by RockyFaher** [comment]
![image](https://user-images.githubusercontent.com/44368671/47400631-fcc23c00-d70b-11e8-80bb-aa813d5c5406.png)

Yah!  Go into the code and modify the win7 Border Transparency to include version 8OS and you can  eliminate the square background tab frame to get a more natural rounded look like so. 

**/* Windows 7 or 8 specific */
@media (-moz-os-version: windows-win8) {
  .tabbrowser-tab {
    background-color: transparent !important;
    border: none !important;
  }**

**Comment by wilfredwee** [comment]
Hi there,

Sorry for the very late reply! Thanks for your feedback, I have made further clarifications in the README in this commit: 73713d8cfef53495e7b78b75859ebc5359e10ef2

As for your issue with Windows 8, I'm glad you found a way to fix it! Unfortunately I don't posses a Windows 8 machine to verify the fix. I will try to get one and incorporate your fix.

Thanks.
-Wilfred.
