### ISSUE TITLE
fixed hover tab length

### ISSUE THREAD

**Issue by moozhub** [wilfredwee/photon-australis#60]
Like the theme. There's one thing that's driving me absolutely bats though (well actually 2). One is when hovering over a tab that's inactive it's expanding the tab length, almost as if it's trying to pop out and pierce my eyes, driving me absolutely nuts, anyway to disable that? The other, which has been brought up in your issues in the past, of having a secondary color for inactive tabs. I know you mentioned this was by choice and you've pointed to #22 as a possible fix, but the code used there is from over a year ago and also doesn't support the dark theme. I would have tried to migrate the changes that were made into the latest version but it seems like more than half of the original document was changed, and CSS isn't my strongest language to begin with. Any chance of help on these two issues (or at least the highly annoying pop out effect)?

**Comment by moozhub** [comment]
Thank you thank you thank you!!! I can work with this, was checking out your github here and noticed you forked the dark theme too but hadn't been updated in awhile. Appreciate the hasty response, the pop out thing was about to drive me insane. Thanks again.

**Comment by qingxiang-jia** [comment]
I also tried your fork. It's so nice. I am gonna keep it.

**Comment by wilfredwee** [comment]
Glad y'all worked this out!
