### ISSUE TITLE
Is it possible to change curve radius?

### ISSUE THREAD

**Issue by jpcaltabiano** [wilfredwee/photon-australis#63]
Making the switch to Firefox and love this feature. However, I like the look of the new Chrome curved tabs (with straight sides and rounded corners) a bit more than the slanted-side tabs I have now in Firefox. What can I add or change in my userChrome.css file I copied from this repo to change the curvature of the tabs in this fashion?

Thanks

**Comment by wilfredwee** [comment]
Hi there, you might be interested in this excellent project instead: https://github.com/muckSponge/MaterialFox

This project aims to loosely replicate the old Firefox curves :)

**Comment by jpcaltabiano** [comment]
This is great, thank you so much!

**Comment by jpcaltabiano** [comment]
This is great, thank you so much!
