### ISSUE TITLE
extension support using theme_experiment

### ISSUE THREAD

**Issue by maxwell-clarke-intranel** [wilfredwee/photon-australis#64]
Hi,

Firefox 63 added support for themes to modify the firefox ui. 
https://blog.mozilla.org/addons/2018/08/31/extensions-in-firefox-63
https://bugzilla.mozilla.org/show_bug.cgi?id=1347207

I don't think these themes can be published but it might still be easier to install this way?

Worth considering, if you didn't know about it already.

**Comment by wilfredwee** [comment]
Unfortunately Firefox theme is very limited in what it can do, and Firefox is not planning to support extensive theming capabilities in the future.
