### ISSUE TITLE
selected/unselected tab text colours (help?)

### ISSUE THREAD

**Issue by Gucek** [wilfredwee/photon-australis#66]
this works almost perfectly in my FF65+ right now, tiny question, tho - how to change active tab's text (and shadow) colour?
in particular: I use this theme https://addons.mozilla.org/en-US/firefox/addon/blue-mozilla-firefox/ and it works great with "userChrome-default.css" with only exceptions being active tab - which is white-on-white with only shadow visible + closing 'x' being invisible.. and no inactive tabs outlines - but with this I definitely can live. :)

**Comment by wilfredwee** [comment]
For changing the tab's font color, you might want to try this:
```
.tab-text.tab-label {
  color: black;
}
```

For further customization help, I'm sure Reddit (https://www.reddit.com/r/FirefoxCSS/ )will be of a better help than I every could be :)
