### ISSUE TITLE
Tab hover, new tab issue and borders.

### ISSUE THREAD

**Issue by NootTP** [wilfredwee/photon-australis#67]
I made selected tab transparent. Now when I hover on the left or right side of the selected tab I have this problem:
![imgp](https://user-images.githubusercontent.com/48473701/54188937-0e389480-44b1-11e9-80c0-81a891148502.jpg)

Another two problems is that there seem to be a border on bottom of selected tab. Also after clicking new tab button, the tab stop like in image below:
![imgp3](https://user-images.githubusercontent.com/48473701/54191487-50180980-44b6-11e9-9960-63b2bb00c0f9.jpg)

I also would like to have border around selected tab and under inactive tabs like this:
![imgp2](https://user-images.githubusercontent.com/48473701/54190725-b3a13780-44b4-11e9-8311-e56af1d57f4f.jpg)
Picture above is from different theme and selected tab still has line under it. I just used photoshop to give an example.

**Comment by wilfredwee** [comment]
Looks like you've already found some help here: https://www.reddit.com/r/FirefoxCSS/comments/b06riy/problem_with_hover_on_tabs_new_tab_cutout_tab/

Unfortunately the customization you seek for is not trivial to implement.
