### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by savagesunday** [wilfredwee/photon-australis#68]
I've created the chrome folder, then inside that I created the userChrome.css folder. Then I created a plain text userChrome.css file. I copied and pasted the code, but it is not working. Am I missing something? 

Also, if I can get this working, is it possible to add code to make it possible to move the tabs below the bookmark bar/url bar?

**Comment by wilfredwee** [comment]
Hi there, you should rename your folder to `chrome`

As for your second question, I’m sure there’s a way to do it, you should ask for advice from r/FirefoxCSS in Reddit.

**Comment by savagesunday** [comment]
> 
> 
> Hi there, you should rename your folder to `chrome`
> 
> As for your second question, I’m sure there’s a way to do it, you should ask for advice from r/FirefoxCSS in Reddit.

I already did that. I followed the instructions as you said. I made the chrome folder inside the root directory. Inside that, I made the userChrome.css sheet. I made sure it's not a .txt. Then I pasted your code, but it's not doing anything.
