### ISSUE TITLE
Followed all directions, code not working

### ISSUE THREAD

**Issue by savagesunday** [wilfredwee/photon-australis#69]
Hi there, you should rename your folder to `chrome`

As for your second question, I’m sure there’s a way to do it, you should ask for advice from r/FirefoxCSS in Reddit.

_Originally posted by @wilfredwee in https://github.com/wilfredwee/photon-australis/issues/68#issuecomment-473420677_

I already did that. I followed the instructions as you said. I made the chrome folder inside the root directory. Inside that, I made the userChrome.css sheet. I made sure it's not a .txt. Then I pasted your code, but it's not doing anything.

If it helps, I'm using Firefox 65.0.2 (64 bit). I also read we needed to put a namespace or something at the beginning, but since you didn't include that in the code, I left it out.

**Comment by wilfredwee** [comment]
Hello, unfortunately I can't help you much in this area. Perhaps there's some other configuration in your system causing this. Perhaps Reddit will be of better help: https://www.reddit.com/r/firefox/
