### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stevebaines** [wilfredwee/photon-australis#70]
Hi Wilfred,

Thanks for the photon-australis tabs.  Really nice professional finish. The only usability comment I have is that with the light and standard themes, the unselected tabs are hard to see because the text is white and the background is transparent and if there is another window behind Firefox pretty much the only thing visible is the favicon.

Is there a simple way of keeping the mouseover shading permanently?  I'm not bothered about changing anything major but this tweak would help.

Kind regards,
Steve.

**Comment by wilfredwee** [comment]
Hi Steve,

Sorry for the (very) late reply. You might want to try modifying the `userChrome.css` file by applying the styles with `:hover` properties to those without the hover properties. If you get stuck I've seen many helpful people over at Reddit: https://www.reddit.com/r/FirefoxCSS/

**Comment by wilfredwee** [comment]
You might be interested in this as well: #22
