### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by crosh0** [wilfredwee/photon-australis#71]
this thing only works on compact and normal density, please make it so that it works on touch density

**Comment by PizzaLovingNerd** [comment]
I agree, Australis looks better when using the touch density, this would be a great improvement

**Comment by wilfredwee** [comment]
Thanks for the suggestion. Unfortunately supporting touch density requires quite a lot of work in customizing the curved tabs' SVG. I'd be happy to accept pull requests but I don't have plans to support it at the moment.

**Comment by wilfredwee** [comment]
#49
