### ISSUE TITLE
Sexy curved tabs not so much

### ISSUE THREAD

**Issue by Grumpy2** [wilfredwee/photon-australis#73]
Well, I'm new to css. Long time programmer - Basic, Fortran & Cobol, however css is a whole different animal. 

Install this on my PC and loved it. Installed it on my wife's PC and new tab is missing.

![Capture](https://user-images.githubusercontent.com/50888736/58574961-0c4fb900-81f6-11e9-89bc-4c1f14cafcd6.PNG)

As far as I can tell, everything on both PC's is the same- Win7, Firefox 66.0.5, default theme.

What am I missing?

**Comment by michaelchen21** [comment]
Is it possible your wife has Customize > Density set to Touch instead of Normal?

**Comment by Grumpy2** [comment]
Michael: 

Thank you for responding. 

It appeared to be a hardware issue. I reinstalled Win7 and now, 
Firefox doesn't recognize userChrome.css at all. Still troubleshooting the problem. I'm not 
sure where to go from here, however you can close this issue. 

Thanks again for your help. 

Regards, 

D.M. De Haven (aka Grumpy2)

**Comment by Grumpy2** [comment]
Michael: 

Well, I solved the problem. Out of ideas, I backed up Firefox on my PC and restored on my wife's PC. Bingo, everything works as it should. I can't explain this - maybe you can. 

I added more code to your curved tabs .css to make it my own - see below. Not being a css coder, I found snippets of code here and there that I was able implement with some playing around. 


Not visible here, I was also able to change that stupid tab-throbber as well. 

Regards, 

D.M. De Haven (aka Grumpy2)

**Comment by wilfredwee** [comment]
Hi Grumpy2,

Sorry I don't have a Windows 7 machine to test. Could you please provide a screenshot of how it looks now? I'm curious how does this work on the old Windows theme.

**Comment by michaelchen21** [comment]
To clarify, I’m not the developer here; wilfredwee is. I’m just a fan.

**Comment by Grumpy2** [comment]
Wilfred: 

I'm not sure I understand your question. I'm assuming you are referencing the email I just set to Michael Chen. 
I assumed that he was the developer - my bad. 

I won't know how this would work in the " old Windows theme " as I don't know what you are referring to as the "old Windows theme". 

All of my four PC's have been upgraded to Win7, so I have know way to run this on WinXP, if that is what you are asking. 

This is it how it looks now - running on Win7, Firefox 66.05 out of the box Light theme. 


If I can be of further help, I'll be happy to try. 

Regards, 

D.M. De Haven (akaGrumpy2)
