### ISSUE TITLE
No longer works with FF 68?

### ISSUE THREAD

**Issue by zeroalias74** [wilfredwee/photon-australis#74]
Just found your code and wanted to try it. Copy the code over to the CSS file and restart but the tabs remain the same. Does this code work on FF 68.0.1 which is the latest?

**Comment by wilfredwee** [comment]
It should work if you've performed the steps correctly. From FF69 onwards you'll have to enable a special flag in `about:config`, read more here: https://www.reddit.com/r/FirefoxCSS/comments/brmi8v/psa_firefox_v69_users_will_have_to_set_a_pref_to/

**Comment by zeroalias74** [comment]
my apology, I forgot I had updated to the beta, which in fact requires the new flag to be enabled. All works fine, thanks again!
