### ISSUE TITLE
Firefox 68esr

### ISSUE THREAD

**Issue by wicatfly** [wilfredwee/photon-australis#76]
looks terrible.....I made it step by step,anything others should be noticed?
![捕获](https://user-images.githubusercontent.com/55010685/64469474-66510a80-d165-11e9-8f46-023bbbd724f4.JPG)

**Comment by wilfredwee** [comment]
Hi there, the latest release should remove the bottom border on the inactive tabs. https://github.com/wilfredwee/photon-australis/releases/latest

**Comment by wicatfly** [comment]
Thanks for your help! That's working now,but can you take a look at the
both side of the top of the active tab, I'm sorry for my poor English, I
don't know how to describe it, if you can understand what I mean, I'll
appreciate it!

Wilfred Wee <notifications@github.com> 于2019年9月7日周六 下午3:54写道：

**Comment by wicatfly** [comment]
Thanks for your help! That's working now,but can you take a look at the
both side of the top of the active tab, I'm sorry for my poor English, I
don't know how to describe it, if you can understand what I mean, I'll
appreciate it!

Wilfred Wee <notifications@github.com> 于2019年9月7日周六 下午3:54写道：

**Comment by wicatfly** [comment]
Wilfred Wee <notifications@github.com> 于2019年9月7日周六 下午3:54写道：

**Comment by wicatfly** [comment]
I just remember a word for this, sawtooth, left and right both on the top
of active tab

Wilfred Wee <notifications@github.com> 于2019年9月7日周六 下午3:54写道：
