### ISSUE TITLE
2 suggestion

### ISSUE THREAD

**Issue by Saadi1988** [wilfredwee/photon-australis#81]
Hi,
1. Please make new tab (+) part 's mouser over background white or minimum lightner. And it can be a circle.
2. Please make url-bar 's corners curved. but not too much.

Thanks.

**Comment by wilfredwee** [comment]
Sorry, I've decided to make this project on bugfix maintenance only. Feel free to ask if the kind folks at https://www.reddit.com/r/FirefoxCSS/ are willing to help out.
