### ISSUE TITLE
I'm depressed that I can't make it

### ISSUE THREAD

**Issue by yannickBurky** [wilfredwee/photon-australis#83]
MacOS 10.15.2 Catalina 
Firefox 71.0 (64-bit)

First I followed Github's directions. Then I went to the Mozilla page indicated, I used their doc, tested all the themes, all the possibilities ...  
Is it possible that it doesn't work with this configuration?

Thx

**Comment by wilfredwee** [comment]
It should work. I have a Macbook running Catalina. Make sure you follow the instructions closely.
