### ISSUE TITLE
Mojave problem

### ISSUE THREAD

**Issue by Avalon-V** [wilfredwee/photon-australis#85]
I so NEED this to the very depths of my soul so you are a saint for doing it. But I can't make it work. I think I am putting the wrong stuff in the chrome folder. My first question is: Since I'm using Mojave, should the css file be named `userChrome.css` or `userChrome-dark.css`? Next I'm not certain my copied code is right (because it doesn't have line numbers); is that a concern. My best guess is "no."
   I have tried copy/paste(s) of your code and also have tried dragging your document into my chrome folder. But I still have the anti-sexy blocky tabs. There are more iterations for me to try concerning the document (name(s), text(s), theme possibilities) but I am frustrated in ignorance.
   I really want to use this with the Default theme because I can't read any of the Mojave dark-mode stuff. 
   Can you give me some saintly advice? I haven't coded since 1978-1986 (when we made computers out of rocks and twine) and I am whelmed.

**Comment by wilfredwee** [comment]
I'm using Mojave at work so it should work.

1. It must be named `userChrome.css`.
2. It should not have line numbers.

To avoid mistakes, you can try to copy the raw code, e.g.: https://raw.githubusercontent.com/wilfredwee/photon-australis/master/userChrome-dark.css

Cmd + A to select all, then copy.

Then paste it in the `userChrome.css` file. Make sure that you follow the instructions properly and have your `chrome` folder in the right place, and `userChrome.css` file inside the `chrome` folder.

**Comment by Avalon-V** [comment]
Thanks so much. That should speed me along quite a bit.
