### ISSUE TITLE
Does not change the appearance of Firefox tabs

### ISSUE THREAD

**Issue by mzavattaro** [wilfredwee/photon-australis#87]
Currently using Firefox 72.0.2 on macOS.
Followed the instructions as per the Github repo, however when restarting Firefox, it doesn't change the tab appearance.

Does this method still work for Firefox?

**Comment by wilfredwee** [comment]
Hi there, yes it should still work. I have both MacOS Mojave and Catalina and they are working. Ensure that you have followed the instructions carefully.
