### ISSUE TITLE
Does this work on macOS catalina?

### ISSUE THREAD

**Issue by jakepq** [wilfredwee/photon-australis#88]
I followed all the steps in the readme however, the modification did not work.

I am using macOS Catalina with the latest version of Firefox.

Thanks

**Comment by wilfredwee** [comment]
Hi there,

It definitely works with Catalina as I'm using it in my personal machine. Please ensure you have created the file in the correct directory, with the correct name and file extension.

**Comment by jakepq** [comment]
I am using the light theme and I copied and pasted the .css file into the newly created chrome folder in the in-use root directory and renamed it userChrome.css, it did not work. How do I create a .css file on a mac?

**Comment by jakepq** [comment]
Nevermind, the issue was that when I clicked "show in finder" on the correct item, it took me to an incorrect file path. 

Thanks for your assistance!
