### ISSUE TITLE
Part of a text appear next to the favicon when a tab pinned.

### ISSUE THREAD

**Issue by qhungg289** [wilfredwee/photon-australis#89]
![image](https://user-images.githubusercontent.com/42641045/76827904-6471ad80-6852-11ea-9f02-8f6bcad27f79.png)
Firefox 74.0
Windows 10
Default theme

**Comment by wilfredwee** [comment]
Hi, can I know what's your monitor resolution, and scaling factor?

**Comment by qhungg289** [comment]
> 
> 
> Hi, can I know what's your monitor resolution, and scaling factor?

1920x1080, running at 150% scaling factor.

**Comment by wilfredwee** [comment]
This should be fixed with the newest code. Thanks.
