### ISSUE TITLE
Tab edges are not curved while dragging tabs around

### ISSUE THREAD

**Issue by Exploder98** [wilfredwee/photon-australis#9]
When I drag tabs, they are square. This happens at least on OS X, haven't tested on Windows yet, but I guess they will be there square too.

**Comment by rotan-hanrahan** [comment]
Doesn't happen on Win10.

**Comment by Exploder98** [comment]
That's interesting. Are you using the dark theme?

**Comment by rotan-hanrahan** [comment]
Tested further. On Win10 it happens in Dark but not in Light or Default. I was using Light at the time.

**Comment by Luarst** [comment]
Go into the css, and find ".tabbrowser-tab > .tab-stack > .tab-background"
Add this to it.. it is missing in the dark theme:
  background-color: transparent !important;

**Comment by Exploder98** [comment]
Yep, that's it. Thanks.

**Comment by wilfredwee** [comment]
Thanks for the investigation @Luarst ! I forgot to update the dark theme when I added the default and white theme.

This release fixes it: https://github.com/wilfredwee/photon-australis/tree/v0.2.2

Closing this!
