### ISSUE TITLE
Tab Doesn't Touch The Bottom

### ISSUE THREAD

**Issue by Suckmylittlefinger** [wilfredwee/photon-australis#90]
![image](https://user-images.githubusercontent.com/62370299/77034337-0cd16000-6980-11ea-8cee-d80cd9b320e6.png)

Followed the guide and didn't touch the code

**Comment by wilfredwee** [comment]
Hi, are you using the 'Touch' density? This CSS doesn't support Touch density, I've only tested it with Normal density, but it appears to work well with Compact density as well.

**Comment by Suckmylittlefinger** [comment]
Ah thank you! I didn't even realize I messed with the density. Thanks a million
