### ISSUE TITLE
Curved tabs and release compatibily 

### ISSUE THREAD

**Issue by alonevino** [wilfredwee/photon-australis#94]
I tried (hard) to install the mod on a windows 7 with Fx 68.7.0esr and on a windows 10 with Fx 75.0. None of them work. I point out that other userChrome.css mods do work (please don't misunderstand me: I'm non merging them). Any hint/suggestion ?

**Comment by wilfredwee** [comment]
Hi, make sure that they're in the correct folder, and has the correct file name. Since you have a working userChrome.css mod, try deleting all the text in the file (don't delete the file), and copy and paste the code from this project to that file.
