### ISSUE TITLE
Linux not working

### ISSUE THREAD

**Issue by phackwer** [wilfredwee/photon-australis#95]
Tried on Linux, default dark theme, didn't work.

**Comment by wilfredwee** [comment]
Hi there, I've tested it on Ubuntu 20.04 and it works. Looks like you may have missed some parts of the instructions or there are other configuration issues.

**Comment by mitchweaver** [comment]
It is working for me however with some graphical glitches.

This was done on Ubuntu w/ Gnome.

screenshot, notice the black line at the bottom of the current tab:
![image](https://wvr.sh/u/0uaB.png)

Any ideas how to fix?

**Comment by wilfredwee** [comment]
Glad to hear!
