### ISSUE TITLE
How do I modify the tab curve?

### ISSUE THREAD

**Issue by thefferon** [wilfredwee/photon-australis#96]
Thank you for your post here: https://support.mozilla.org/en-US/questions/1223318 and here in GitHub. I followed your instructions and was easily able to get back curved tabs in Firefox Dev v77. Awesome.

What I would really like to do with tabs is have them look like the stock boxy tabs at the bottom of the tab (where the tab bar meets the main toolbar), and at the top of the tabs have just a slight rounded corner (as opposed to the file-folder-like swoopy thing):

<img width="584" alt="Screen Shot 2020-05-13 at 1 45 07 PM" src="https://user-images.githubusercontent.com/313712/81846601-596c8e00-9520-11ea-8623-071cbfd707f6.png">

As a noob (who would break things if I tried playing with userChrome.css), I am hoping you can point me toward exactly which items in the css file would create the change I am looking for, without breaking everything else.

If you have time and don't mind pointing this out, I'd be very grateful.

Thanks

**Comment by wilfredwee** [comment]
Hi there, achieving what you're looking for is not trivial. You'll need to edit the SVG embedded in the CSS file.
