### ISSUE TITLE
Solid colour bar underneath tabs

### ISSUE THREAD

**Issue by diggitydingdong** [wilfredwee/photon-australis#97]
![image](https://user-images.githubusercontent.com/8567231/82132668-80c7a180-9825-11ea-9e45-0379b595f091.png)

Hi, I just recently installed firefox (running win10) as an alternative to chrome again and wanted to get the curves that I remember from previous versions. Your solution worked wonderfully, however, I can't seem to notice this solid colour bar under my tabs (it's the same on the dark theme, I haven't tried default). I had a quick look through all the issues and I can't seem to find anyone else with it. Cheers.

**Comment by diggitydingdong** [comment]
![image](https://user-images.githubusercontent.com/8567231/82133009-c2f2e200-9829-11ea-9184-00288325aedd.png)
I don't know if this is related or not but there's a small notch on the bottom of the new tab button when i hover over it. If it's not related i can open a new issue

**Comment by wilfredwee** [comment]
Hi, are you using Touch density? Touch density is not supported by this project unfortunately.

**Comment by diggitydingdong** [comment]
I see. I think that's what I'm using, yeah.
