### ISSUE TITLE
Not working on 76.0.1

### ISSUE THREAD

**Issue by Neiby** [wilfredwee/photon-australis#99]
I believe I have followed the instructions correctly. 

1. I set toolkit.legacyUserProfileCustomizations.stylesheets to true
2. I opened the root folder of my current profile and created a chrome folder
3. I created a new file named userChrome.css and pasted in the config from userChrome-light.css
4. I saved the file and restarted FF, but nothing is different

Did I miss something important?

**Comment by Neiby** [comment]
Nevermind, I figured it out. I think I wasn't clear about where to put the chrome folder. I put it directly in the root folder, but I was supposed to put it inside the folder one level down. Very nice!

**Comment by wilfredwee** [comment]
Glad to hear!
